package bot.seven.WLR.gui

import java.awt.Color

object GuiColors {
    val PRIMARY_BLUE: Int = Color(40, 120, 200).rgb
    val PRIMARY_BLUE_BRIGHT: Int = Color(80, 160, 255).rgb
    val PRIMARY_BLUE_DARK: Int = Color(20, 90, 150).rgb
    val LIGHT_BLUE: Int = Color(100, 180, 255).rgb

    val SCREEN_BACKGROUND: Int = Color(15, 15, 18).rgb
    val COMPONENT_BACKGROUND: Int = Color(25, 25, 28).rgb
    val COMPONENT_BACKGROUND_HOVER: Int = Color(35, 35, 40).rgb
    val COMPONENT_BACKGROUND_DISABLED: Int = Color(20, 20, 23).rgb

    val COMPONENT_BORDER: Int = Color(40, 40, 45).rgb
    val COMPONENT_BORDER_BLUE: Int = PRIMARY_BLUE_DARK
    val COMPONENT_BORDER_FOCUSED_BLUE: Int = PRIMARY_BLUE_BRIGHT

    val TEXT_PRIMARY: Int = Color(220, 220, 225).rgb
    val TEXT_SECONDARY: Int = Color(180, 180, 180).rgb
    val TEXT_ACCENT: Int = PRIMARY_BLUE_BRIGHT
    val TEXT_DISABLED: Int = Color(100, 100, 105).rgb
    val TEXT_ON_BLUE_BACKGROUND: Int = Color(240, 240, 240).rgb

    val TRANSPARENT_BLACK_VERY_LIGHT: Int = Color(0, 0, 0, 20).rgb
    val TRANSPARENT_BLACK_LIGHT: Int = Color(0, 0, 0, 45).rgb
    val TRANSPARENT_BLACK_MEDIUM: Int = Color(0, 0, 0, 75).rgb

    private val _TEXT_PRIMARY_AWT = Color(TEXT_PRIMARY, true)
    val TRANSPARENT_TEXT_PRIMARY_VERY_LIGHT: Int = Color(_TEXT_PRIMARY_AWT.red, _TEXT_PRIMARY_AWT.green, _TEXT_PRIMARY_AWT.blue, 20).rgb
    val TRANSPARENT_TEXT_PRIMARY_LIGHT: Int = Color(_TEXT_PRIMARY_AWT.red, _TEXT_PRIMARY_AWT.green, _TEXT_PRIMARY_AWT.blue, 35).rgb

    private val _PRIMARY_BLUE_BRIGHT_AWT_FOR_HIGHLIGHT = Color(PRIMARY_BLUE_BRIGHT, true)
    val TRANSPARENT_BLUE_VERY_LIGHT_HIGHLIGHT: Int = Color(_PRIMARY_BLUE_BRIGHT_AWT_FOR_HIGHLIGHT.red, _PRIMARY_BLUE_BRIGHT_AWT_FOR_HIGHLIGHT.green, _PRIMARY_BLUE_BRIGHT_AWT_FOR_HIGHLIGHT.blue, 30).rgb


    val TAB_BAR_BACKGROUND: Int = Color(20, 20, 22).rgb
    val TAB_BUTTON_BACKGROUND_INACTIVE: Int = TAB_BAR_BACKGROUND
    val TAB_BUTTON_BACKGROUND_HOVER: Int = COMPONENT_BACKGROUND_HOVER
    val TAB_BUTTON_BACKGROUND_ACTIVE: Int = PRIMARY_BLUE
    val TAB_BUTTON_TEXT_INACTIVE: Int = Color(160, 160, 165).rgb
    val TAB_BUTTON_TEXT_HOVER: Int = TEXT_PRIMARY
    val TAB_BUTTON_TEXT_ACTIVE: Int = TEXT_ON_BLUE_BACKGROUND
    val TAB_BAR_BORDER: Int = Color(30, 30, 33).rgb
    val TAB_SCROLL_BUTTON_BG: Int = Color(35, 35, 40).rgb
    val TAB_SCROLL_BUTTON_HOVER_BG: Int = Color(45, 45, 50).rgb
    val TAB_SCROLL_BUTTON_ARROW: Int = TEXT_PRIMARY

    val CATEGORY_TITLE_TEXT: Int = TEXT_ON_BLUE_BACKGROUND
    private val _PRIMARY_BLUE_DARK_AWT_FOR_CAT_BG = Color(PRIMARY_BLUE_DARK, true)
    val CATEGORY_TITLE_BACKGROUND: Int = Color(_PRIMARY_BLUE_DARK_AWT_FOR_CAT_BG.red, _PRIMARY_BLUE_DARK_AWT_FOR_CAT_BG.green, _PRIMARY_BLUE_DARK_AWT_FOR_CAT_BG.blue, 200).rgb
    private val _PRIMARY_BLUE_AWT_FOR_CAT_BORDER = Color(PRIMARY_BLUE, true)
    val CATEGORY_TITLE_BORDER: Int = Color(_PRIMARY_BLUE_AWT_FOR_CAT_BORDER.red, _PRIMARY_BLUE_AWT_FOR_CAT_BORDER.green, _PRIMARY_BLUE_AWT_FOR_CAT_BORDER.blue, 180).rgb
    val CATEGORY_SEPARATOR_LINE: Int = Color(_PRIMARY_BLUE_DARK_AWT_FOR_CAT_BG.red, _PRIMARY_BLUE_DARK_AWT_FOR_CAT_BG.green, _PRIMARY_BLUE_DARK_AWT_FOR_CAT_BG.blue, 150).rgb

    val SCROLLBAR_BG: Int = Color(20, 20, 22).rgb
    val SCROLLBAR_THUMB: Int = PRIMARY_BLUE
    val MODERN_SCROLLBAR_THUMB_HOVER: Int = PRIMARY_BLUE_BRIGHT

    val CHECKBOX_BOX: Int = COMPONENT_BACKGROUND
    val CHECKBOX_BOX_HOVER: Int = COMPONENT_BACKGROUND_HOVER
    val CHECKBOX_CHECK: Int = PRIMARY_BLUE_BRIGHT

    val DROPDOWN_ARROW: Int = TEXT_PRIMARY
    val DROPDOWN_BACKGROUND_OPEN: Int = Color(20, 20, 22, 250).rgb
    val DROPDOWN_ITEM_TEXT: Int = TEXT_PRIMARY
    private val _P_BLUE_AWT_FOR_DROPDOWN = Color(PRIMARY_BLUE, true)
    val DROPDOWN_ITEM_HOVER_BG: Int = Color(_P_BLUE_AWT_FOR_DROPDOWN.red, _P_BLUE_AWT_FOR_DROPDOWN.green, _P_BLUE_AWT_FOR_DROPDOWN.blue, 90).rgb
    val DROPDOWN_ITEM_SELECTED_BG: Int = Color(_P_BLUE_AWT_FOR_DROPDOWN.red, _P_BLUE_AWT_FOR_DROPDOWN.green, _P_BLUE_AWT_FOR_DROPDOWN.blue, 130).rgb

    val SLIDER_TRACK: Int = Color(35, 35, 40).rgb
    val SLIDER_TRACK_FILLED: Int = PRIMARY_BLUE
    val SLIDER_KNOB_BLUE_THEME: Int = PRIMARY_BLUE
    val SLIDER_KNOB_HOVER_BLUE_THEME: Int = PRIMARY_BLUE_BRIGHT
    val SLIDER_KNOB: Int = SLIDER_KNOB_BLUE_THEME
    val SLIDER_KNOB_HOVER: Int = SLIDER_KNOB_HOVER_BLUE_THEME

    val TEXTFIELD_BACKGROUND: Int = Color(20, 20, 22).rgb
    val TEXTFIELD_BORDER: Int = COMPONENT_BORDER
    val TEXTFIELD_BORDER_FOCUSED: Int = PRIMARY_BLUE_BRIGHT
    val TEXTFIELD_TEXT: Int = TEXT_PRIMARY

    val MODERN_PRIMARY_BACKGROUND: Int = SCREEN_BACKGROUND
    val MODERN_SECONDARY_BACKGROUND: Int = COMPONENT_BACKGROUND

    val MODERN_ACCENT_PRIMARY: Int = PRIMARY_BLUE_BRIGHT
    val MODERN_ACCENT_SECONDARY: Int = PRIMARY_BLUE

    val MODERN_UI_ELEMENT_BORDER: Int = COMPONENT_BORDER
    val MODERN_DIVIDER_COLOR: Int = Color(30, 30, 33).rgb

    val MODERN_COMPONENT_HOVER: Int = COMPONENT_BACKGROUND_HOVER
    val MODERN_COMPONENT_ACTIVE: Int = LIGHT_BLUE
    val MODERN_COMPONENT_DISABLED_BG: Int = COMPONENT_BACKGROUND_DISABLED

    val BUTTON_MODERN_BACKGROUND: Int = PRIMARY_BLUE
    val BUTTON_MODERN_BACKGROUND_HOVER: Int = PRIMARY_BLUE_BRIGHT
    val BUTTON_MODERN_TEXT: Int = TEXT_ON_BLUE_BACKGROUND

    val TITLE_BAR_BACKGROUND: Int = Color(18, 18, 20).rgb
    val TITLE_BAR_TEXT: Int = TEXT_PRIMARY
    val TITLE_BAR_SEPARATOR: Int = PRIMARY_BLUE_DARK

    private val _P_BLUE_BRIGHT_AWT_FOR_GLOW = Color(PRIMARY_BLUE_BRIGHT, true)
    val PRIMARY_BLUE_BRIGHT_GLOW_EFFECT: Int = Color(_P_BLUE_BRIGHT_AWT_FOR_GLOW.red, _P_BLUE_BRIGHT_AWT_FOR_GLOW.green, _P_BLUE_BRIGHT_AWT_FOR_GLOW.blue, 80).rgb

    private val _SCREEN_BG_AWT_FOR_SHADOW = Color(SCREEN_BACKGROUND, true)
    val SUBTLE_SHADOW_COLOR: Int = Color(
        (_SCREEN_BG_AWT_FOR_SHADOW.red - 3).coerceAtLeast(0),
        (_SCREEN_BG_AWT_FOR_SHADOW.green - 3).coerceAtLeast(0),
        (_SCREEN_BG_AWT_FOR_SHADOW.blue - 3).coerceAtLeast(0),
        120
    ).rgb
}